### ISSUE TITLE
What is the difference to tpope/vim-scriptease zS?

### ISSUE THREAD

**Issue by kiryph** [benknoble/vim-synstax#1]
https://github.com/tpope/vim-scriptease provides

> `zS`: Show the active syntax highlighting groups under the cursor.

What can your plugin compared to scriptease?

**Comment by benknoble** [comment]
While I haven't used scriptease, I've certainly heard of it and am considering experimenting with it.

The difference is synstax don't provide any default mappings (you get to pick), and it provides a functional interface for syntax-related items _only_. synstax focuses on syntax, and thus is fairly lightweight if that is all you need.

P.S. synstax provides a nice "message" when there aren't any syntax groups under the cursor
